# Generated by Django 6.0.2 on 2026-02-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('disease', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
