# Generated by Django 6.0.2 on 2026-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phno',
            field=models.IntegerField(max_length=10),
        ),
    ]
