# Generated by Django 6.0.2 on 2026-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_hospital_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
